### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by leethargo**
fix some typos.

### CODE REVIEW

**Comment by blegat** [comment]
Thanks a lot :)

**Comment by leethargo** [comment]
I was actually hoping that the documentation would at that point explain a compatibility bridge between `JuMP` and `Polyhedra`.

**Comment by blegat** [comment]
I will add that soon then :)
The current code in `Polyhedra` is not good. I have something better locally (still need to push).
The basic idea is that that it adds methods for `linprog` and `loadproblem!` for accepting `HRepresentation` or `Polyhedron` describing the feasible set.
Now solver have 3 alternatives

* only implement the support for the classical `loadproblem!` with lb <= Ax <= ub, l <= x <= b. A call `loadproblem!` with an `HRepresentation` will be transformed to a classical call.
* only implement the support for `loadproblem!` with an `HRepresentation`. A classical call will be transformed to a call with `HRepresentation` very cheaply using the `LPHRepresentation` (which is a representation of a polyhedron using lb <= Ax <= ub, l <= x <= b so no copy, not transformation needed). This is the case for CDDLib's LP solver for example.
* support both :)

**Comment by blegat** [comment]
I still need to update `CDDLib` and `LRSLib` for the new architecture of `Polyhedra` then I'll push everything and document `Polyhedra` better :)

**Comment by leethargo** [comment]
I'm looking forward to it. Even without talking to any solvers, just defining the model in JuMP and enumerating vertices or visualizing 2d/3d projections is already worth a lot!

**Comment by blegat** [comment]
@leethargo Using JuMP feasible sets is now supported and documented :)

**Comment by leethargo** [comment]
Thanks for the update. My use case for it is already gone, but I'll keep it in mind for the next time!

**Pull request merged**
